In [1]:
DATA_PATH = "../dataset/Cleand_Data.pkl"
MODEL_PATH = "../models/RandomForest.h5"
SCALER_PATH = "../models/Scaler.h5"

In [2]:
import pandas as pd
import joblib

In [3]:
df = pd.read_pickle(DATA_PATH)
df.head()

                  DevType                           \
      Academic researcher Data or business analyst
54451                   1                        0
37550                   1                        0
49646                   1                        0
47422                   1                        1
5139                    1                        0

                                                                            \
      Data scientist or machine learning specialist Database administrator
54451                                             0                      0
37550                                             0                      0
49646                                             0                      0
47422                                             0                      0
5139                                              0                      0

                                                                   \
      DevOps specialist Developer, QA or test Developer, back-end
54451                 0                     0                   0
37550                 0                     0                   0
49646                 0                     0                   0
47422                 0                     0                   0
5139                  0                     0                   0

                                                     \
      Developer, desktop or enterprise applications
54451                                             0
37550                                             1
49646                                             0
47422                                             0
5139                                              0

                                                                        ...  \
      Developer, embedded applications or devices Developer, front-end  ...
54451                                           0                    0  ...
37550                                           0                    0  ...
49646                                           0                    0  ...
47422                                           0                    0  ...
5139                                            0                    0  ...

      MiscTechWorkedWith                                                 \
                 Node.js Pandas Puppet React Native TensorFlow Teraform
54451                  1      0      0            1          0        0
37550                  0      0      0            0          0        0
49646                  0      0      0            0          0        0
47422                  0      0      0            0          0        0
5139                   0      0      0            0          0        0


      Torch/PyTorch Unity 3D Unreal Engine Xamarin
54451             0        0             0       0
37550             0        0             0       0
49646             0        0             0       0
47422             0        0             0       0
5139              0        0             0       0

[5 rows x 90 columns]

In [4]:
x = df.drop("DevType",axis=1)
skills = x.columns.droplevel(0).to_list()
skills

['Assembly',
 'Bash/Shell/PowerShell',
 'C',
 'C#',
 'C++',
 'Dart',
 'Go',
 'HTML/CSS',
 'Haskell',
 'Java',
 'JavaScript',
 'Julia',
 'Kotlin',
 'Objective-C',
 'PHP',
 'Perl',
 'Python',
 'R',
 'Ruby',
 'Rust',
 'SQL',
 'Scala',
 'Swift',
 'TypeScript',
 'VBA',
 'Cassandra',
 'Couchbase',
 'DynamoDB',
 'Elasticsearch',
 'Firebase',
 'IBM DB2',
 'MariaDB',
 'Microsoft SQL Server',
 'MongoDB',
 'MySQL',
 'Oracle',
 'PostgreSQL',
 'Redis',
 'SQLite',
 'ASP.NET',
 'ASP.NET Core',
 'Angular',
 'Angular.js',
 'Django',
 'Drupal',
 'Express',
 'Flask',
 'Gatsby',
 'Laravel',
 'React.js',
 'Ruby on Rails',
 'Spring',
 'Symfony',
 'Vue.js',
 'jQuery',
 '.NET',
 '.NET Core',
 'Ansible',
 'Apache Spark',
 'Chef',
 'Cordova',
 'Flutter',
 'Hadoop',
 'Keras',
 'Node.js',
 'Pandas',
 'Puppet',
 'React Native',
 'TensorFlow',
 'Teraform',
 'Torch/PyTorch',
 'Unity 3D',
 'Unreal Engine',
 'Xamarin']

In [17]:
dictionary_record = {}
for skill in skills:
    dictionary_record[skill] = 0
dictionary_record

{'Assembly': 0,
 'Bash/Shell/PowerShell': 0,
 'C': 0,
 'C#': 0,
 'C++': 0,
 'Dart': 0,
 'Go': 0,
 'HTML/CSS': 0,
 'Haskell': 0,
 'Java': 0,
 'JavaScript': 0,
 'Julia': 0,
 'Kotlin': 0,
 'Objective-C': 0,
 'PHP': 0,
 'Perl': 0,
 'Python': 0,
 'R': 0,
 'Ruby': 0,
 'Rust': 0,
 'SQL': 0,
 'Scala': 0,
 'Swift': 0,
 'TypeScript': 0,
 'VBA': 0,
 'Cassandra': 0,
 'Couchbase': 0,
 'DynamoDB': 0,
 'Elasticsearch': 0,
 'Firebase': 0,
 'IBM DB2': 0,
 'MariaDB': 0,
 'Microsoft SQL Server': 0,
 'MongoDB': 0,
 'MySQL': 0,
 'Oracle': 0,
 'PostgreSQL': 0,
 'Redis': 0,
 'SQLite': 0,
 'ASP.NET': 0,
 'ASP.NET Core': 0,
 'Angular': 0,
 'Angular.js': 0,
 'Django': 0,
 'Drupal': 0,
 'Express': 0,
 'Flask': 0,
 'Gatsby': 0,
 'Laravel': 0,
 'React.js': 0,
 'Ruby on Rails': 0,
 'Spring': 0,
 'Symfony': 0,
 'Vue.js': 0,
 'jQuery': 0,
 '.NET': 0,
 '.NET Core': 0,
 'Ansible': 0,
 'Apache Spark': 0,
 'Chef': 0,
 'Cordova': 0,
 'Flutter': 0,
 'Hadoop': 0,
 'Keras': 0,
 'Node.js': 0,
 'Pandas': 0,
 'Puppet': 0,
 'React Native': 0,
 'TensorFlow': 0,
 'Teraform': 0,
 'Torch/PyTorch': 0,
 'Unity 3D': 0,
 'Unreal Engine': 0,
 'Xamarin': 0}

# Now, testing new record by passing it to our trained model

In [19]:
new_record = ['Pandas', 'TensorFlow', 'Torch/PyTorch', 'Python', 'Keras']
for i in new_record:
    dictionary_record[i] = 1

dictionary_record

{'Assembly': 0,
 'Bash/Shell/PowerShell': 0,
 'C': 0,
 'C#': 0,
 'C++': 0,
 'Dart': 0,
 'Go': 0,
 'HTML/CSS': 0,
 'Haskell': 0,
 'Java': 0,
 'JavaScript': 0,
 'Julia': 0,
 'Kotlin': 0,
 'Objective-C': 0,
 'PHP': 0,
 'Perl': 0,
 'Python': 1,
 'R': 0,
 'Ruby': 0,
 'Rust': 0,
 'SQL': 0,
 'Scala': 0,
 'Swift': 0,
 'TypeScript': 0,
 'VBA': 0,
 'Cassandra': 0,
 'Couchbase': 0,
 'DynamoDB': 0,
 'Elasticsearch': 0,
 'Firebase': 0,
 'IBM DB2': 0,
 'MariaDB': 0,
 'Microsoft SQL Server': 0,
 'MongoDB': 0,
 'MySQL': 0,
 'Oracle': 0,
 'PostgreSQL': 0,
 'Redis': 0,
 'SQLite': 0,
 'ASP.NET': 0,
 'ASP.NET Core': 0,
 'Angular': 0,
 'Angular.js': 0,
 'Django': 0,
 'Drupal': 0,
 'Express': 0,
 'Flask': 0,
 'Gatsby': 0,
 'Laravel': 0,
 'React.js': 0,
 'Ruby on Rails': 0,
 'Spring': 0,
 'Symfony': 0,
 'Vue.js': 0,
 'jQuery': 0,
 '.NET': 0,
 '.NET Core': 0,
 'Ansible': 0,
 'Apache Spark': 0,
 'Chef': 0,
 'Cordova': 0,
 'Flutter': 0,
 'Hadoop': 0,
 'Keras': 1,
 'Node.js': 0,
 'Pandas': 1,
 'Puppet': 0,
 'React Native': 0,
 'TensorFlow': 1,
 'Teraform': 0,
 'Torch/PyTorch': 1,
 'Unity 3D': 0,
 'Unreal Engine': 0,
 'Xamarin': 0}

In [21]:
new_record = list(dictionary_record.values())
new_record

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0]

In [23]:
model = joblib.load(MODEL_PATH)
scaler = joblib.load(SCALER_PATH)

In [25]:
model.predict(scaler.transform([new_record]))

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
predictions = model.predict_proba(scaler.transform([new_record]))
posative_probs = [prob[0][1] for prob in predictions]
pd.Series(posative_probs, index=df["DevType"].columns).sort_values(ascending=False)

Data scientist or machine learning specialist    0.942222
Academic researcher                              0.328000
Scientist                                        0.241111
Developer, embedded applications or devices      0.070000
Developer, back-end                              0.066667
Data or business analyst                         0.023333
DevOps specialist                                0.013333
Developer, full-stack                            0.005556
Database administrator                           0.000000
Developer, QA or test                            0.000000
Developer, desktop or enterprise applications    0.000000
Developer, front-end                             0.000000
Developer, game or graphics                      0.000000
Developer, mobile                                0.000000
Engineer, data                                   0.000000
System administrator                             0.000000
dtype: float64